server:
  port: ${PORT:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway


spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
    registerWithEureka: false

ribbon:
  eureka:
    enabled: true

zuul:
  prefix: /api
  routes:
    articles:
      path: /articles/**
      serviceId: article-service
    authors:
      path: /authors/**
      serviceId: author-service

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false