spring:
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:file:./test'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: creditcalc.agent
    password: '${GMAIL_APP_PASSWORD}'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: true

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

server:
  servlet:
    session:
      cookie:
        same-site: lax

  cors:
    allowed-origins-pattern: "http://localhost:[8080,5500],http://127.0.0.1:[8080,5500]"

  error:
    whitelabel:
      enabled: true
    path: /error


  host: http://localhost:8080

  mail:
    name: 'Credit Calculator'
    address: creditcalc.agent@gmail.com

  storage:
    data-directory: 'data'