spring:
  application:
    name: calculator-service

  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:file:./test'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

server:
  servlet:
    session:
      cookie:
        same-site: lax

  cors:
    allowed-origins-pattern: "http://localhost:[8080,5500,8761,8081],http://127.0.0.1:[8080,5500]"

  error:
    whitelabel:
      enabled: true
    path: /error


  host: http://localhost:8080

  storage:
    data-directory: 'data'

  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
