spring:
  application:
    name: submit-service

  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:file:./test'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

server:
  servlet:
    session:
      cookie:
        same-site: lax

  error:
    whitelabel:
      enabled: true
    path: /error

  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
